was too slow

diff --git a/git-shared-submodule-update b/git-shared-submodule-update
--- a/git-shared-submodule-update
+++ b/git-shared-submodule-update
@@ -56,15 +56,12 @@ cmd_update () {
 
     if [ $# = 0 ]
     then
-        git ls-files -z --stage | while IFS= read -r -d '' line
+        git ls-files --stage | while read -r mode _ _ path
         do
-            echo "$line" | while read -r mode _ _ path
-            do
-                if [ "$mode" = "160000" ]
-                then
-                    __submodule_update_path "$path" "$update_opts" || die "failed: git submodule-update $path"
-                fi
-            done
+            if [ "$mode" = "160000" ]
+            then
+                __submodule_update_path "$path" "$update_opts" || die "failed: git submodule-update $path"
+            fi
         done
 
     else
